---
- name: Ensure data directory is present.
  file:
    path: "{{ vault_data_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ vault_data_directory_user }}"
    group: "{{ vault_data_directory_group }}"

- name: Ensure log directory is present.
  file:
    path: "{{ vault_log_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ vault_log_directory_user }}"
    group: "{{ vault_log_directory_group }}"

- name: Install autocompletion.
  command: "{{ item[0] }} -autocomplete-install"
  become: "{{ item[1] }}"
  with_nested:
    - "{{ hashicorp_product_selection }}"
    - [ 'true', 'false' ]
  register: autoinstall_cmd
  changed_when:
    - not 'already installed' in autoinstall_cmd.stderr
  failed_when:
    - autoinstall_cmd.rc != 0
    - not 'already installed' in autoinstall_cmd.stderr
